import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}

// export default function NavLayout({ children }: LayoutProps<"/">) {
//   return (
//     <div className="flex min-h-screen flex-col">
//       <h1 className="bg-sky-300 text-2xl text-black">Navigation Header</h1>
//       {children}
//       <h2 className="bg-sky-300 text-2xl text-black">Footer</h2>
//     </div>
//   );
// }
